apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "gophprofile.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "gophprofile.fullname" . }}

    spec:
      serviceAccountName: {{ include "gophprofile.fullname" . }}

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001

      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          resources:
{{ toYaml .Values.resources | indent 12 }}
