apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}

data:
  APP_ENV: {{ .Values.environment | default "production" }}
  HTTP_PORT: "8080"
  METRICS_PORT: "9090"
  LOG_LEVEL: {{ .Values.logLevel | default "info" }}

  # Database
  {{- if .Values.postgresql }}
  POSTGRES_HOST: {{ .Values.postgresql.host | default "postgres" }}
  POSTGRES_PORT: {{ .Values.postgresql.port | default "5432" | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | default "gophprofile" }}
  {{- end }}

  # Message Queue
  {{- if .Values.rabbitmq }}
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | default "rabbitmq" }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | default "5672" | quote }}
  {{- end }}

  # Object Storage
  {{- if .Values.minio }}
  MINIO_ENDPOINT: {{ .Values.minio.endpoint | default "minio:9000" }}
  MINIO_BUCKET: {{ .Values.minio.bucket | default "avatars" }}
  {{- end }}

  # OpenTelemetry
  {{- if .Values.otel }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | default "http://otel-collector:4317" }}
  OTEL_SERVICE_NAME: {{ include "gophprofile.fullname" . }}
  OTEL_TRACES_EXPORTER: otlp
  {{- end }}
