apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gophprofile.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: migrate/migrate:v4.17.0
          args:
            - -path=/migrations
            - -database=$(DB_URL)
            - up

          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "gophprofile.fullname" . }}
                  key: DB_URL

          volumeMounts:
            - name: migrations
              mountPath: /migrations

      volumes:
        - name: migrations
          configMap:
            name: {{ include "gophprofile.fullname" . }}-migrations
