apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gophprofile.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - migrate
          envFrom:
            - secretRef:
                name: {{ include "gophprofile.fullname" . }}
