apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gophprofile.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}

spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}

  selector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
