apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_URL: {{ required "DB_URL is required" .Values.secrets.dbUrl | quote }}
  RABBIT_URL: {{ required "RABBIT_URL is required" .Values.secrets.rabbitUrl | quote }}
  S3_KEY: {{ required "S3_KEY is required" .Values.secrets.s3Key | quote }}
  S3_SECRET: {{ required "S3_SECRET is required" .Values.secrets.s3Secret | quote }}
