apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gophprofile.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}

automountServiceAccountToken: false
