apiVersion: v1
kind: Secret
metadata:
  name: gophprofile-api
  namespace: gophprofile

type: Opaque

stringData:
  POSTGRES_USER: gophprofile
  POSTGRES_PASSWORD: gophprofile
  POSTGRES_DB: avatars

  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest

  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

  S3_KEY: minioadmin
  S3_SECRET: minioadmin
  S3_BUCKET: avatars
