apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gophprofile-api
  namespace: gophprofile

spec:
  selector:
    matchLabels:
      app: gophprofile-api

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
